### ISSUE TITLE
No type checks in other files when exporting `typeof MyModel.prototype` without another `typeof`.

### ISSUE THREAD

**Issue by luxferresum** [typed-ember/ember-typings#58]
Basically this should throw a typing error:

```ts
function makefoo(f : Foo) : string {
  return f.bar;
}
```

And this is how `Foo` is defined:

```ts
const Foo = Ember.Object.extend({
  name: "Hallo"
});

type Foo = typeof Foo.prototype;
export default Foo;
```

As workaround this can be done:

```ts
function makefoo2(f : typeof Foo) : string {
  return f.bar;
}
```

This correctly outputs:
> app/controllers/application.ts(10,12): error TS2339: Property 'bar' does not exist on type 'Readonly<typeof Object> & (new () => { name: string; } & Object) & (new (...args: any[]) => { nam...'

[This repo can be used as reproduction](https://github.com/luxferresum/typescript-ember-data-demo/blob/master/app/controllers/application.ts).

Ping @dwickern @chriskrycho since we discussed this in slack.

**Comment by chriskrycho** [comment]
It took me a few, but the problem is the `typeof Foo.prototype` in the original declaration. (IIRC, this is a case where our types required that then but have since been fixed.) The correct way to write the original declaration is like so:

```ts
const Foo = Ember.Object.extend({
  name: "Hallo"
});

type Foo = typeof Foo;
export default Foo;
```

This correctly resolves with an error in the other module.
