### ISSUE TITLE
WARNINGs when using 'get()'

### ISSUE THREAD

**Issue by peabnuts123** [typed-ember/ember-typings#73]
Hi there. I am trying to get `ember-cli-typescript` up and running but I'm encountering some rather fundamental issues. Something about the type declarations of `get()` is funny.

I am encountering a few issues. The first of which is in a class-based pattern (which I'd like to use, ideally):

```ts
import Controller from '@ember/controller';
import { get, computed } from '@ember/object';

export default class ApplicationController extends Controller {
  value: string;
  
  init() {
    console.log(get(this, 'value'));
  }
}
```

I get a warning on the line `get(this, 'value')`, specifically on the token `this`:

```
WARNING: ember-typescript/controllers/application.ts(8,21): error TS2345: Argument of type 'this' is not assignable to parameter of type 'ComputedProperties<{ value: string; init: () => void; replaceRoute: (name: string, ...args: any[]...'.
```

It can't seem to assign type `ApplicationController` to `ComputedProperties<T>`. I can't quite grasp the intent with this type. 

The second use-case is when using a more standard `Controller.extend` pattern:

```ts
import Controller from '@ember/controller';
import { get, computed } from '@ember/object';

export default Controller.extend({
  value: 2,

  debug: computed('value', function() {
    let value = get(this, 'value');
  }),
});
```

I get a warning warning on the line `get(this, 'value')`, again, specifically on the token `this`: 

```
WARNING: ember-typescript/controllers/application.ts(8,27): error TS2345: Argument of type '"value"' is not assignable to parameter of type 'never'.
```

This seems to be because `this` is of type `any` as defined here: 
```ts
    type ComputedPropertyGetterFunction<T> = (this: any, key: string) => T;
```

in `@types/ember/index.d.ts` line 76.

It's worth mentioning that this app completely functions in either scenario but it seems kind of misconfigured somehow as this is a completely vanilla app trying to do something completely standard. Any ideas what the issue is here?

**Comment by peabnuts123** [comment]
Oh and FYI my packages@versions are as follows:

```
├── @types/ember@2.8.5
├── @types/ember-testing-helpers@0.0.3
├── @types/rsvp@4.0.1
├── broccoli-asset-rev@2.6.0
├── ember-ajax@3.0.0
├── ember-cli@2.17.2
├── ember-cli-app-version@3.1.3
├── ember-cli-babel@6.11.0
├── ember-cli-dependency-checker@2.1.0
├── ember-cli-eslint@4.2.3
├── ember-cli-htmlbars@2.0.3
├── ember-cli-htmlbars-inline-precompile@1.0.2
├── ember-cli-inject-live-reload@1.7.0
├── ember-cli-qunit@4.2.1
├── ember-cli-shims@1.2.0
├── ember-cli-sri@2.1.1
├── ember-cli-typescript@1.0.6
├── ember-cli-uglify@2.0.0
├── ember-data@2.17.0
├── ember-export-application-global@2.0.0
├── ember-load-initializers@1.0.0
├── ember-resolver@4.5.0
├── ember-source@2.17.0
├── ember-welcome-page@3.1.1
├── loader.js@4.6.0
└── typescript@2.6.2

**Comment by chriskrycho** [comment]
Hi @peabnuts123, thanks for the detailed writeup!

These are, sadly, well-known issues to me personally, and I'm working on a blog post (probably live tomorrow morning) which walks through the solution (below) for them in some detail. Also note that, thankfully, a *lot* of this will go away when the [ES5 Getters RFC][rfc] lands (probably Ember 3.1 or 3.2)

In the meantime, the workaround is to explicitly annotate the `this` type for the methods and *especially* for computed property functions:

```ts
import Controller from '@ember/controller';
import { get, computed } from '@ember/object';

export default class ApplicationController extends Controller {
  value: string;
  
  // `this: ApplicationController` is what you need to make this work as expected.
  init(this: ApplicationController) {
    console.log(get(this, 'value'));
  }
}
```

Things will generally *not* work especially well in the old-style `.extends()` invocations, because there's no named type to give to the `this` in that case.

Today's workaround in *that* case (which loses you type safety but makes things type-check) is to do `(this as any).get(...)` there. Once [this DefinitelyTyped PR][pr] merges and is live—probably the next day or two—you'll be able to do that with `get(this as any, ...)` as well. And, since you're on the latest here and with TypeScript, you can also use `// @ts-ignore` comments where necessary. (It's really unfortunate that all of these escape hatches remain necessary, but they should be getting much better in the next three or four months.)

This will be in the README as well as in a long example blog post sometime in the week. (I'm moving into a new house 🏘️ on Thursday, so everything will be a bit spotty along the way, though.)

[rfc]: https://github.com/emberjs/rfcs/blob/master/text/0281-es5-getters.md
[pr]: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/22905

**Comment by peabnuts123** [comment]
Thank for the quick response there Chris! Looking forward to that Getters RFC. The best solution I've found so far is to do something like 

```ts
  const self = this as ApplicationController

  let value = get(self, value);
```

in functions, but it's definitely bringing back old jQuery memories. I will try out your `this: ApplicationController` recommendation. Good to hear things are always on the move, though :)
