### ISSUE TITLE
[ember-data]: Type is referenced directly or indirectly in the fulfillment callback of its own 'then' method

### ISSUE THREAD

**Issue by theseyi** [typed-ember/ember-typings#74]
When using async/await on an ember Route model, awaiting the result of `store.findRecord` throws the following typescript exception. (in the comment below)

```typescript
async model(): Promise<any> {
  const store = get(this, 'store'); 
  await store.findRecord('someStoreRecord', 1); // Type is referenced directly or indirectly in the fulfillment callback of its own 'then' method
  }
```
Using a `.then` works as expected. This issue arises with as mentioned, using `async/await`

Could this be an issue with the return type definition for `store.findRecord` which is ` PromiseObject<T> & T`?

**Comment by dwickern** [comment]
Is it still broken on ts@next?

**Comment by cptran777** [comment]
Recreated this same issue using ts@2.7.0-dev.20180118

**Comment by theseyi** [comment]
@dwickern yea, still broken

**Comment by dwickern** [comment]
I had a quick look. It's caused by the self-recursive nature of [PromiseObject](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/ember-data/index.d.ts#L866) and [PromiseArray ](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/ember-data/index.d.ts#L855]) (they are promises which resolve to _themselves_). To fix this we might have to break some pathological scenarios around promise proxies, but I won't lose any sleep over it.

I'll open a PR in the next couple of days if nobody else gets to it.

**Comment by dwickern** [comment]
Fixed by https://github.com/DefinitelyTyped/DefinitelyTyped/pull/23238
